# -*- coding: utf-8 -*-
"""Smolagent using Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsZc1O1CZH9agVlO2N-fBx3rjNolGOLM
"""

!pip  install smolagents -U
!pip install duckduckgo-search

import smolagents
print(smolagents.__version__)

from huggingface_hub import notebook_login
notebook_login()

"""Finding books for implementing Al-ML in the workplace, using smolagents

For the model, we'll rely on InferenceClientModel, which provides access to Hugging Face's Inference API. The default model is "Owen/Qwen2.5-Coder-328-Instruct", which is performant and available for fast inference, but you can select any compatible model fro the Hub.
"""

#Running an agent is quite straightforward
from smolagents import CodeAgent, DuckDuckGoSearchTool, InferenceClientModel
agent = CodeAgent(tools= [DuckDuckGoSearchTool()], model=InferenceClientModel(provider="together"))
agent.run("Search for the best book recommendations for implementing AI in the workplace.")

